# Generated by Django 5.2 on 2025-04-29 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHab', models.CharField(blank=True, max_length=15, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['nombreHab'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(blank=True, max_length=20, verbose_name='Habilidad')),
                ('habilidadesRol', models.ManyToManyField(to='empleados.habilidades')),
            ],
            options={
                'verbose_name': 'Rol/Trabajo',
                'verbose_name_plural': 'Roles/Trabajos',
                'ordering': ['nombreRol'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmp', models.CharField(max_length=20, verbose_name='Nombre del Empleado')),
                ('apellidoEmp', models.CharField(max_length=20, verbose_name='Apellido del Empleado')),
                ('departamentoEmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamentos.departamento')),
                ('rolEmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.rol')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidoEmp', 'nombreEmp'],
            },
        ),
    ]
