# Generated by Django 5.2 on 2025-05-06 23:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_fechanac_alter_rol_nombrerol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Texto de Observaciones'),
        ),
    ]
