# Generated by Django 5.2 on 2025-05-20 21:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='observaciones',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='nombreHab',
            field=models.CharField(blank=True, max_length=35, verbose_name='Habilidad'),
        ),
    ]
