# Generated by Django 5.2 on 2025-05-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombreRol',
            field=models.CharField(blank=True, max_length=40, verbose_name='Rol'),
        ),
    ]
