# Generated by Django 5.2 on 2025-06-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['rolEmp', 'apellidoEmp', 'nombreEmp'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
