# Generated by Django 5.2 on 2025-06-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellidoEmp', 'nombreEmp', 'rolEmp'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
