# Generated by Django 5.2 on 2025-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDto', models.CharField(blank=True, max_length=50, verbose_name='Departamento')),
                ('siglaDto', models.CharField(max_length=4, unique=True, verbose_name='Sigla')),
                ('isActivo', models.BooleanField(default=False, verbose_name='¿Está activo?')),
                ('pisoDto', models.CharField(blank=True, max_length=5, verbose_name='Piso')),
                ('oficinaDto', models.CharField(blank=True, max_length=10, verbose_name='Oficina N°')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['siglaDto'],
            },
        ),
    ]
